run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - dupl
    - ginkgolinter
    - goconst
    - gocyclo
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam

issues:
  exclude-use-default: false
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
